language: python

sudo: false

env:
  matrix:
    - LUA="lua 5.1"
    - LUA="lua 5.1"    ZLIB=lzlib
    - LUA="lua 5.1"    ZLIB=lua-zlib
    - LUA="lua 5.2"
    - LUA="lua 5.2"    ZLIB=lzlib
    - LUA="lua 5.2"    ZLIB=lua-zlib
    - LUA="lua 5.3"
    - LUA="lua 5.3"    ZLIB=lzlib
    - LUA="lua 5.3"    COMPAT53=no
    # lua-zlib is currently unavailable for lua5.3 https://github.com/brimworks/lua-zlib/issues/28
    - LUA="luajit @"
    - LUA="luajit @"   ZLIB=lzlib
    - LUA="luajit @"   ZLIB=lua-zlib
    - LUA="luajit 2.0"
    - LUA="luajit 2.0" ZLIB=lzlib
    - LUA="luajit 2.0" ZLIB=lua-zlib
    - LUA="luajit 2.1"
    - LUA="luajit 2.1" ZLIB=lzlib
    - LUA="luajit 2.1" ZLIB=lua-zlib

branches:
  only:
    - master

before_install:
  - pip install hererocks
  - hererocks ~/hererocks -r^ --$LUA # Install latest LuaRocks version
                              # plus the Lua version for this build job
                              # into 'here' subdirectory
  - export PATH=$PATH:~/hererocks/bin # Add directory with all installed binaries to PATH
  - eval `luarocks path --bin`
  - luarocks install luacheck
  - luarocks install luacov-coveralls
  - luarocks install busted

install:
  - luarocks install --only-deps http-scm-0.rockspec
  - if [ "$ZLIB" = "lzlib" ]; then luarocks install lzlib; fi
  - if [ "$ZLIB" = "lua-zlib" ]; then luarocks install lua-zlib; fi
  - if [ "$COMPAT53" = "no" ]; then luarocks remove compat53; fi

script:
  - luacheck .
  - busted -c

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.cache/hererocks
