language: python

arch:
 - amd64
 - ppc64le
 
sudo: false

env:
  matrix:
    - LUA="lua 5.1"
    - LUA="lua 5.1"    ZLIB=lzlib
    - LUA="lua 5.1"    ZLIB=lua-zlib
    - LUA="lua 5.2"
    - LUA="lua 5.2"    ZLIB=lzlib
    - LUA="lua 5.2"    ZLIB=lua-zlib
    - LUA="lua 5.3"
    - LUA="lua 5.3"    ZLIB=lzlib
    - LUA="lua 5.3"    ZLIB=lua-zlib
    - LUA="lua 5.3"    COMPAT53=no
    - LUA="lua 5.3"    LUA_CFLAGS="-DLUA_INT_TYPE=LUA_INT_INT"
    - LUA="luajit @"
    - LUA="luajit @"   ZLIB=lzlib
    - LUA="luajit @"   ZLIB=lua-zlib
    - LUA="luajit 2.0"
    - LUA="luajit 2.0" ZLIB=lzlib
    - LUA="luajit 2.0" ZLIB=lua-zlib
    - LUA="luajit 2.1"
    - LUA="luajit 2.1" ZLIB=lzlib
    - LUA="luajit 2.1" ZLIB=lua-zlib
jobs:
    exclude:
        - arch: ppc64le
          env: LUA="luajit @"
        - arch: ppc64le
          env: LUA="luajit @"   ZLIB=lzlib    
        - arch: ppc64le
          env: LUA="luajit @"   ZLIB=lua-zlib
        - arch: ppc64le
          env: LUA="luajit 2.0"       
        - arch: ppc64le
          env: LUA="luajit 2.0" ZLIB=lzlib       
        - arch: ppc64le
          env: LUA="luajit 2.0" ZLIB=lua-zlib
        - arch: ppc64le
          env: LUA="luajit 2.1"
        - arch: ppc64le
          env: LUA="luajit 2.1" ZLIB=lzlib
        - arch: ppc64le
          env: LUA="luajit 2.1" ZLIB=lua-zlib    

branches:
  only:
    - master

before_install:
  - pip install hererocks
  - hererocks ~/hererocks -r^ --$LUA --cflags=$LUA_CFLAGS
  - export PATH=$PATH:~/hererocks/bin
  - eval $(luarocks path --bin)
  - luarocks install luacheck
  - luarocks install https://raw.githubusercontent.com/andremm/typedlua/master/typedlua-scm-1.rockspec
  - luarocks install luacov-coveralls
  - luarocks install busted

install:
  - luarocks install --only-deps http-scm-0.rockspec
  - if [ "$ZLIB" = "lzlib" ]; then luarocks install lzlib; fi
  - if [ "$ZLIB" = "lua-zlib" ]; then luarocks install lua-zlib; fi
  - if [ "$COMPAT53" = "no" ]; then luarocks remove compat53; fi

script:
  - luacheck .
  - tlc -o /dev/null spec/require-all.lua
  - busted -c

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.cache/hererocks
